openapi: 3.1.0
info:
  title: Stoplight news-v1
  version: '1.0'
  summary: Retrieves news articles from various news sources
  description: The api retrieves the articles from the database and arranges them by date/site/category or specific article IDs
  contact:
    name: Ryan
    email: grantom.ryan@gmail.com
servers:
  - url: 'http://127.0.0.1:4010'
    description: Hosted Server
paths:
  /news-sources:
    parameters: []
    get:
      summary: Get all News Sources
      tags:
        - news-source
      responses:
        '200':
          description: Retrieved list of sources
          content:
            application/json:
              schema:
                $ref: ../models/news-source.yaml
              examples: {}
          headers: {}
        '401':
          description: Unauthorized to retrieve data
          content:
            application/json:
              schema:
                $ref: ../models/common-error.yaml
        '':
          content:
            application/json:
              schema:
                $ref: ../models/news-source.yaml
          description: Successfully retrieved all of the sources
      operationId: get-news-sources
      description: Retrieves list of all news sources in database
      parameters:
        - $ref: '#/components/parameters/limit'
      x-internal: false
      security:
        - API Key - 1: []
    post:
      summary: Add a News Source
      operationId: add-news-site
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: ../models/news-source.yaml
              examples:
                Add a news source example response:
                  value:
                    id: 1
                    site: www.yahoo.com
                    category:
                      - politics
                      - sports
                      - fun
                      - idk
        '401':
          description: Unauthorized to add news source
          content:
            application/json:
              schema:
                $ref: ../models/common-error.yaml
      description: '#Add a site to the list of news sources'
      tags:
        - news-source
      parameters:
        - $ref: '#/components/parameters/Content-Type'
        - schema:
            type: string
          in: header
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/news-source.yaml
  '/news-sources/{site}':
    parameters:
      - name: site
        in: path
        required: true
        schema:
          type: string
        description: Name of site to retrieve news articles from
    put:
      summary: Update News Source
      operationId: update-news-source
      responses:
        '200':
          description: Successfully updated.
          content:
            application/json:
              schema:
                $ref: ../models/news-source.yaml
        '404':
          description: News Source not found
          content:
            application/json:
              schema:
                $ref: ../models/common-error.yaml
      description: |
        # Update a news source categories available, or name
         *Markdown formatting works here*
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/news-source.yaml
      tags:
        - news-source
        - site
      parameters:
        - $ref: '#/components/parameters/Content-Type'
        - $ref: '#/components/parameters/dynamic'
    delete:
      summary: Delete a news source
      operationId: delete-news-source
      responses:
        '200':
          description: Successfully deleted source
          content:
            application/json:
              schema:
                $ref: ../models/news-source.yaml
        '404':
          description: Source not found
          content:
            application/json:
              schema:
                $ref: ../models/common-error.yaml
      description: Delete a news source or categories from the database
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/news-source.yaml
      tags:
        - news-source
  /news:
    get:
      summary: Get news from all sources
      tags:
        - news-article
      responses: {}
      operationId: get-news
      description: Get news from all sources in database
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/news-article.yaml
      parameters:
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/Content-Type'
    parameters: []
  '/news/{article-id}':
    parameters:
      - $ref: '#/components/parameters/article-id'
    get:
      summary: Get news article by id
      tags:
        - news-article
      responses: {}
      operationId: get-news-article-id
      description: retrieve a single news article
  '/news/{date}':
    parameters:
      - schema:
          type: string
        name: date
        in: path
        required: true
      - $ref: '#/components/parameters/date'
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-news-date
  '/news/{category}':
    parameters:
      - $ref: '#/components/parameters/category'
    get:
      summary: Get news by category
      operationId: get-news-category
      responses:
        '200':
          description: OK
      tags:
        - news-article
  '/news/{site}':
    parameters:
      - $ref: '#/components/parameters/site'
    get:
      summary: Get news from site
      tags:
        - news-article
        - site
      responses: {}
      operationId: get-news-site
      description: gather news from a specific site
  '/news/{site}/{category}':
    parameters:
      - $ref: '#/components/parameters/site'
      - $ref: '#/components/parameters/category'
    get:
      summary: Get news from site by category
      tags:
        - news-article
        - site
      responses: {}
      operationId: get-news-site-category
      description: gather news from a specific site and category
  /change:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-change
components:
  schemas:
    news-article:
      $ref: ../models/news-article.yaml
    news-source:
      $ref: ../models/news-source.yaml
  parameters:
    limit:
      name: limit
      in: query
      schema:
        type: integer
      description: Number of news articles returned
    category:
      name: category
      in: path
      required: true
      schema:
        type: string
      description: Category of News Articles
    article-id:
      name: article-id
      in: path
      required: true
      schema:
        type: string
      description: ID of News Article
    site:
      name: site
      in: path
      required: true
      schema:
        type: string
      description: Name of site to retrieve news articles from
    date:
      name: date
      in: path
      required: true
      schema:
        type: string
      description: Date of which to retrieve news articles
    Content-Type:
      name: Content-Type
      in: header
      required: false
      schema:
        type: string
        default: application/json
      description: application/json
    dynamic:
      name: dynamic
      in: header
      required: false
      schema:
        type: string
        default: 'true'
      description: true/false
  responses:
    '404':
      description: Content Not Found
      content:
        application/json:
          schema:
            $ref: ../models/common-error.yaml
      headers: {}
  securitySchemes:
    API Key - 1:
      name: API Key
      type: apiKey
      in: query
