openapi: 3.1.0
info:
  title: news-v1
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /news:
    parameters: []
    get:
      summary: Get News from all Sources
      tags: []
      responses:
        '200':
          description: Retrieved list of articles
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/news-article'
              examples: {}
        '401':
          description: Unauthorized to retrieve data
          content:
            application/json:
              schema:
                $ref: ../models/common-error.yaml
      operationId: get-all-news
      description: Retrieves list of all news articles in database
      parameters:
        - $ref: '#/components/parameters/limit'
    post:
      summary: Add a News Source
      operationId: add-news-site
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/news-source'
      description: Add a site to the list of news sources
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/news-source.yaml
            examples: {}
    delete:
      summary: Delete a News Source
      operationId: delete-news-site
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/news-source.yaml
      description: Deletes a site from the list of sources
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/news-source.yaml
    put:
      summary: Update News Source
      operationId: put-news
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/news-source'
      description: 'Update a news source categories available, or name'
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/news-source.yaml
  '/news/{date}':
    parameters:
      - $ref: '#/components/parameters/date'
    get:
      summary: Get News on Specific Date
      tags: []
      responses: {}
      operationId: get-news-on-date
      description: gather news from a specific date
  '/news/{site}':
    parameters:
      - $ref: '#/components/parameters/site'
    get:
      summary: Get news from site
      tags: []
      responses: {}
      operationId: get-news-site
      description: gather news from a specific site
  '/news/{site}/{category}':
    parameters:
      - $ref: '#/components/parameters/site'
      - $ref: '#/components/parameters/category'
    get:
      summary: Get news from site by category
      tags: []
      responses: {}
      operationId: get-news-site-category
      description: gather news from a specific site and category
  '/news/{category}':
    parameters:
      - $ref: '#/components/parameters/category'
    get:
      summary: Get news by category
      operationId: get-news-category
      responses:
        '200':
          description: OK
  '/news/{article-id}':
    parameters:
      - $ref: '#/components/parameters/article-id'
    get:
      summary: Get news article by id
      tags: []
      responses: {}
      operationId: get-news-article-id
      description: retrieve a single news article
components:
  schemas:
    news-article:
      $ref: ../models/news-article.yaml
    news-source:
      $ref: ../models/news-source.yaml
  parameters:
    limit:
      name: limit
      in: query
      schema:
        type: integer
      description: Limit of news articles returned
    category:
      name: category
      in: path
      required: true
      schema:
        type: string
      description: Category of News Articles
    article-id:
      name: article-id
      in: path
      required: true
      schema:
        type: string
      description: ID of News Article
    site:
      name: site
      in: path
      required: true
      schema:
        type: string
      description: Name of site to retrieve news articles from
    date:
      name: date
      in: path
      required: true
      schema:
        type: string
      description: Date of which to retrieve news articles
