openapi: 3.1.0
info:
  title: news-v1
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /news:
    parameters: []
    get:
      summary: Get News from all Sources
      tags: []
      responses:
        '200':
          description: Retrieved list of articles
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/news'
              examples: {}
        '401':
          description: Unauthorized to retrieve data
          content:
            application/json:
              schema:
                $ref: ''
      operationId: get-all-news
      description: Retrieves list of all news articles in database
      parameters:
        - $ref: '#/components/parameters/limit'
    post:
      summary: Add a News Source
      operationId: add-news-site
      responses:
        '200':
          description: OK
      description: Add a site to the list of news sources
    delete:
      summary: Delete a News Source
      operationId: delete-news-site
      responses:
        '200':
          description: OK
      description: Deletes a site from the list of sources
    put:
      summary: Update News Source
      operationId: put-news
      responses:
        '200':
          description: OK
      description: Update a news source
  '/news/{date}':
    parameters:
      - schema:
          type: string
        name: date
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-news-date
      description: gather news from a specific date
  '/news/{site}':
    parameters:
      - schema:
          type: string
        name: site
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-news-site
      description: gather news from a specific site
  '/news/{site}/{category}':
    parameters:
      - schema:
          type: string
        name: site
        in: path
        required: true
      - schema:
          type: string
        name: category
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-news-site-category
      description: gather news from a specific site and category
  '/news/{category}':
    post:
      summary: Create New User
      operationId: post-user
      responses:
        '200':
          description: User Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                New User Bob Fellow:
                  value:
                    id: 12
                    firstName: Bob
                    lastName: Fellow
                    email: bob.fellow@gmail.com
                    dateOfBirth: '1996-08-24'
                    emailVerified: false
                    createDate: '2020-11-18'
        '400':
          description: Missing Required Information
        '409':
          description: Email Already Taken
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                dateOfBirth:
                  type: string
                  format: date
              required:
                - firstName
                - lastName
                - email
                - dateOfBirth
            examples:
              Create User Bob Fellow:
                value:
                  firstName: Bob
                  lastName: Fellow
                  email: bob.fellow@gmail.com
                  dateOfBirth: '1996-08-24'
        description: Post the necessary fields for the API to create a new user.
      description: gather news in a specific category
    parameters:
      - schema:
          type: string
        name: category
        in: path
        required: true
  '/news/{article-id}':
    parameters:
      - schema:
          type: string
        name: article-id
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-news-article-id
      description: retrieve a single news article
components:
  schemas:
    news:
      $ref: ../models/news.yaml
      examples:
        - article-id: 0
          category: string
          title: string
          data: string
          site-name: string
          site-url: string
          date-retrieved: '2019-08-24'
          date-updated: '2019-08-24T14:15:22Z'
      description: model used to collect news articles from different sites
  parameters:
    limit:
      name: limit
      in: query
      schema:
        type: integer
      description: Limit of articles returned
    category:
      name: category
      in: path
      required: true
      schema:
        type: string
    article-id:
      name: article-id
      in: path
      required: true
      schema:
        type: string
    site:
      name: site
      in: path
      required: true
      schema:
        type: string
    date:
      name: date
      in: path
      required: true
      schema:
        type: string
