openapi: 3.1.0
info:
  title: news-v1
  version: '1.0'
  summary: Retrieves news articles from various news sources
  description: The api retrieves the articles from the database and arranges them by date/site/category or specific article IDs
  contact:
    name: Ryan
    email: grantom.ryan@gmail.com
servers:
  - url: 'http://localhost:3000'
paths:
  /news-sources:
    parameters: []
    get:
      summary: Get all News Sources
      tags:
        - news-source
      responses:
        '200':
          description: Retrieved list of sources
          content:
            application/json:
              schema:
                $ref: ../models/news-source.yaml
              examples: {}
        '401':
          description: Unauthorized to retrieve data
          content:
            application/json:
              schema:
                $ref: ../models/common-error.yaml
        '':
          content:
            application/json:
              schema:
                $ref: ../models/news-source.yaml
          description: Successfully retrieved all of the sources
      operationId: get-news-sources
      description: Retrieves list of all news sources in database
      parameters:
        - $ref: '#/components/parameters/limit'
    post:
      summary: Add a News Source
      operationId: add-news-site
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: ../models/news-source.yaml
        '401':
          description: Unauthorized to add news source
          content:
            application/json:
              schema:
                $ref: ../models/common-error.yaml
      description: Add a site to the list of news sources
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/news-source.yaml
            examples: {}
  '/news-sources/{site}':
    parameters:
      - name: site
        in: path
        required: true
        schema:
          type: string
        description: Name of site to retrieve news articles from
    put:
      summary: Update News Source
      operationId: update-news-source
      responses:
        '200':
          description: Successfully updated.
          content:
            application/json:
              schema:
                $ref: ../models/news-source.yaml
        '404':
          description: News Source not found
          content:
            application/json:
              schema:
                $ref: ../models/common-error.yaml
      description: 'Update a news source categories available, or name'
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/news-source.yaml
      tags:
        - news-source
        - site
    delete:
      summary: Delete a news source
      operationId: delete-news-source
      responses:
        '200':
          description: Successfully deleted source
          content:
            application/json:
              schema:
                $ref: ../models/news-source.yaml
        '404':
          description: Source not found
          content:
            application/json:
              schema:
                $ref: ../models/common-error.yaml
      description: Delete a news source or categories from the database
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/news-source.yaml
  /news:
    get:
      summary: Get news from all sources
      tags:
        - news-article
      responses: {}
      operationId: get-news
      description: Get news from all sources in database
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/news-article.yaml
      parameters:
        - $ref: '#/components/parameters/limit'
    parameters: []
  '/news/{article-id}':
    parameters:
      - $ref: '#/components/parameters/article-id'
    get:
      summary: Get news article by id
      tags:
        - news-article
      responses: {}
      operationId: get-news-article-id
      description: retrieve a single news article
  '/news/{date}':
    parameters:
      - $ref: '#/components/parameters/date'
    get:
      summary: Get News on Specific Date
      tags:
        - news-article
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/news-article'
      operationId: get-news-on-date
      description: gather news from a specific date
      parameters:
        - schema:
            type: string
          in: query
  '/news/{category}':
    parameters:
      - $ref: '#/components/parameters/category'
    get:
      summary: Get news by category
      operationId: get-news-category
      responses:
        '200':
          description: OK
      tags:
        - news-article
  '/news/{site}':
    parameters:
      - $ref: '#/components/parameters/site'
    get:
      summary: Get news from site
      tags:
        - news-article
        - site
      responses: {}
      operationId: get-news-site
      description: gather news from a specific site
  '/news/{site}/{category}':
    parameters:
      - $ref: '#/components/parameters/site'
      - $ref: '#/components/parameters/category'
    get:
      summary: Get news from site by category
      tags:
        - news-article
        - site
      responses: {}
      operationId: get-news-site-category
      description: gather news from a specific site and category
components:
  schemas:
    news-article:
      $ref: ../models/news-article.yaml
    news-source:
      $ref: ../models/news-source.yaml
  parameters:
    limit:
      name: limit
      in: query
      schema:
        type: integer
      description: Limit of news articles returned
    category:
      name: category
      in: path
      required: true
      schema:
        type: string
      description: Category of News Articles
    article-id:
      name: article-id
      in: path
      required: true
      schema:
        type: string
      description: ID of News Article
    site:
      name: site
      in: path
      required: true
      schema:
        type: string
      description: Name of site to retrieve news articles from
    date:
      name: date
      in: path
      required: true
      schema:
        type: string
      description: Date of which to retrieve news articles
  responses: {}
